import type { FallbackData } from "@/types";

export const fallbackData: FallbackData = {
  heroConfig: {
    id: "fallback",
    title: "Transformamos Ideas en Experiencias Digitales",
    subtitle:
      "Agencia de desarrollo web especializada en crear sitios modernos, rápidos y optimizados para tu negocio.",
    ctaPrimaryLabel: "Ver Proyectos",
    ctaPrimaryHref: "#proyectos",
    ctaSecondaryLabel: "Contactar",
    ctaSecondaryHref: "#contacto",
    badgeText: "🚀 Diseño + Desarrollo",
    heroImageUrl: "/hero-devices.png",
    active: true,
  },
  projects: [
    {
      id: "1",
      name: "Local Bar & Restaurant",
      slug: "local-bar-restaurant",
      description:
        "Sitio web moderno para restaurante local con menú interactivo, reservas online y galería de fotos.",
      category: "corporate",
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
      imageUrl: "/screenshots/LOCAL.png",
      screenshots: ["/screenshots/LOCAL.png"],
      demoUrl: "https://paginaweblocalejemplo.pages.dev/",
      featured: true,
      order: 1,
    },
    {
      id: "2",
      name: "Barber Shop Premium",
      slug: "barber-shop-premium",
      description:
        "Landing page elegante para barbería con sistema de turnos, galería de cortes y perfiles de barberos.",
      category: "landing",
      technologies: ["Next.js", "React", "CSS Modules", "React Hook Form"],
      imageUrl: "/screenshots/BARBER.png",
      screenshots: ["/screenshots/BARBER.png"],
      demoUrl: "https://barberejemplopagina.pages.dev/",
      featured: true,
      order: 2,
    },
    {
      id: "3",
      name: "Gym & Fitness Landing",
      slug: "gym-fitness-landing",
      description:
        "Landing page dinámica para gimnasio con planes de membresía, horarios de clases y testimonios.",
      category: "landing",
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Animations"],
      imageUrl: "/screenshots/GYM.png",
      screenshots: ["/screenshots/GYM.png"],
      demoUrl: "https://landingpageejemplo.pages.dev/",
      featured: false,
      order: 3,
    },
  ],
  services: [
    { id: "1", name: "Desarrollo Web", description: "Sitios web modernos, rápidos y responsive.", icon: "Code", color: "#7C3AED", features: ["Next.js 14", "React 18", "TypeScript", "Tailwind CSS"], order: 1, active: true },
    { id: "2", name: "E-commerce", description: "Tiendas online completas con gestión de productos y pagos.", icon: "ShoppingCart", color: "#A855F7", features: ["Carrito", "Pagos", "Panel admin", "Inventario"], order: 2, active: true },
    { id: "3", name: "Landing Pages", description: "Páginas optimizadas para conversión y SEO.", icon: "Rocket", color: "#C084FC", features: ["Alto rendimiento", "SEO", "Formularios", "Analytics"], order: 3, active: true },
    { id: "4", name: "Diseño UI/UX", description: "Interfaces atractivas y experiencias intuitivas.", icon: "Palette", color: "#9333EA", features: ["Figma", "Prototipos", "Design System", "Responsive"], order: 4, active: true },
    { id: "5", name: "Apps Web", description: "Aplicaciones web progresivas con funcionalidad offline.", icon: "Smartphone", color: "#7E22CE", features: ["PWA", "Offline", "Push notifications", "Instalable"], order: 5, active: true },
    { id: "6", name: "APIs REST", description: "APIs robustas y escalables para tus proyectos.", icon: "Server", color: "#6B21A8", features: ["Node.js", "Express", "MongoDB", "Docs"], order: 6, active: true },
    { id: "7", name: "Optimización SEO", description: "Mejora el posicionamiento en buscadores.", icon: "Search", color: "#581C87", features: ["Keywords", "Meta tags", "Performance", "Analytics"], order: 7, active: true },
    { id: "8", name: "Hosting & Deploy", description: "Configuración en servidores cloud confiables.", icon: "Cloud", color: "#7C3AED", features: ["Vercel", "Cloudflare", "AWS", "CI/CD"], order: 8, active: true },
    { id: "9", name: "Mantenimiento", description: "Soporte técnico continuo y actualizaciones.", icon: "Wrench", color: "#A855F7", features: ["Updates", "Backup", "Monitoreo", "Seguridad"], order: 9, active: true },
    { id: "10", name: "Consultoría", description: "Asesoramiento estratégico para tu proyecto.", icon: "Lightbulb", color: "#C084FC", features: ["Stack tech", "Arquitectura", "Escalabilidad", "Best practices"], order: 10, active: true },
    { id: "11", name: "Migraciones", description: "Actualiza tu sitio a tecnologías modernas.", icon: "RefreshCw", color: "#9333EA", features: ["Modernización", "Data migration", "Zero downtime", "Testing"], order: 11, active: true },
    { id: "12", name: "Integraciones", description: "Conecta con herramientas y servicios externos.", icon: "Plug", color: "#7E22CE", features: ["CRM", "Email marketing", "Analytics", "Webhooks"], order: 12, active: true },
    { id: "13", name: "Desarrollo Custom", description: "Soluciones a medida para necesidades específicas.", icon: "Zap", color: "#6B21A8", features: ["Requerimientos únicos", "Escalable", "Documentado", "Soporte"], order: 13, active: true },
  ],
  plans: [
    {
      id: "1", name: "Básico", price: 150000, currency: "ARS", period: "proyecto",
      description: "Ideal para pequeños negocios que necesitan presencia online.",
      features: ["Hasta 5 páginas", "Diseño responsive", "Formulario de contacto", "SEO básico", "1 mes de soporte"],
      notIncluded: ["E-commerce", "Panel de administración", "Integraciones avanzadas", "Analytics personalizado"],
      highlighted: false, ctaLabel: "Comenzar", ctaHref: "#contacto", order: 1,
    },
    {
      id: "2", name: "Profesional", price: 300000, currency: "ARS", period: "proyecto",
      description: "Para empresas que buscan destacarse con funcionalidades avanzadas.",
      features: ["Hasta 15 páginas", "Diseño personalizado", "Panel de administración", "SEO avanzado", "3 meses de soporte", "Blog integrado", "Formularios avanzados", "Analytics"],
      notIncluded: ["E-commerce completo", "App mobile"],
      highlighted: true, badge: "Más elegido", ctaLabel: "Solicitar", ctaHref: "#contacto", order: 2,
    },
    {
      id: "3", name: "Enterprise", price: 0, currency: "ARS", period: "proyecto",
      description: "Soluciones completas y personalizadas para grandes proyectos.",
      features: ["Páginas ilimitadas", "Diseño 100% personalizado", "E-commerce completo", "Panel admin avanzado", "SEO enterprise", "6 meses de soporte", "Integraciones API", "Hosting incluido", "Consultoría continua"],
      notIncluded: [],
      highlighted: false, ctaLabel: "Contactar", ctaHref: "#contacto", order: 3,
    },
  ],
  testimonials: [
    { id: "1", name: "Carlos Méndez", role: "Dueño", company: "La Parrilla Local", content: "El equipo de Rumbo superó nuestras expectativas. El sitio es hermoso y funcional, las reservas online aumentaron un 40%.", rating: 5, active: true, order: 1 },
    { id: "2", name: "Martín López", role: "Barbero Principal", company: "Barber Shop Premium", content: "Excelente trabajo. El sistema de turnos online nos ahorró muchísimo tiempo y los clientes lo encuentran súper fácil de usar.", rating: 5, active: true, order: 2 },
    { id: "3", name: "Laura Gómez", role: "Gerente de Marketing", company: "Fitness Center", content: "Profesionales de primera. La landing page convierte muy bien y refleja perfectamente la identidad de nuestra marca.", rating: 5, active: true, order: 3 },
  ],
  faq: [
    { id: "1", question: "¿Cuánto tiempo tarda el desarrollo?", answer: "Varía según la complejidad. Un sitio básico puede estar listo en 2-3 semanas, proyectos más complejos entre 1 y 3 meses. Te damos un estimado preciso después de la consulta inicial.", category: "General", order: 1, active: true },
    { id: "2", question: "¿Ofrecen mantenimiento después de la entrega?", answer: "Sí, todos nuestros planes incluyen soporte gratuito inicial. Luego podés contratar mantenimiento mensual con actualizaciones, backups y soporte técnico prioritario.", category: "Soporte", order: 2, active: true },
    { id: "3", question: "¿Puedo hacer cambios después del lanzamiento?", answer: "Absolutamente. Si tu plan incluye panel de administración, podés actualizar contenido por tu cuenta. Para cambios de diseño o funcionalidad, ofrecemos servicios adicionales.", category: "Funcionalidad", order: 3, active: true },
    { id: "4", question: "¿Los sitios son responsive?", answer: "Sí, todos nuestros sitios están optimizados para verse perfectamente en móviles, tablets y computadoras. El diseño responsive es estándar en todos nuestros proyectos.", category: "Diseño", order: 4, active: true },
    { id: "5", question: "¿Incluyen hosting y dominio?", answer: "El plan Enterprise incluye hosting por 1 año. En los demás planes te asesoramos en la elección y configuración. Recomendamos servicios confiables y te ayudamos con todo el proceso.", category: "Hosting", order: 5, active: true },
    { id: "6", question: "¿Cómo es el proceso de pago?", answer: "Trabajamos con 50% al iniciar y 50% al finalizar. Para proyectos grandes podemos establecer hitos intermedios. Aceptamos transferencias bancarias y Mercado Pago.", category: "Pagos", order: 6, active: true },
  ],
};
